
spring:
    application:
        name: invoice-service
    datasource:
        url: jdbc:mysql://localhost:3308/invoicedb
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    kafka:
        bootstrap-servers: localhost:9092
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    docker:
        compose:
            file: src/main/docker/docker-compose.yml
    web:
        resources:
            add-mappings: false
server:
    port: 8999
    error:
        whitelabel:
            enabled: false
        include-message: always
        include-exception: false
